# This config file contains the compile options for compilation
# of the GSI code on the NOAA HPCS.

# ----------------------------------
# Redefine variables for NOAA HPCS
# ----------------------------------

myhome=/work/03337/tg826358/stampede2/nmmb_lib
COREINC  = $(myhome)/incmod
CORELIB  = $(myhome)
INCsfcio = $(COREINC)/sfcio_4
INCsigio = $(COREINC)/v2.0.1/incmod/sigio_v2.0.1_4
INCnemsio= $(COREINC)/nemsio
INCw3    = $(COREINC)/w3emc_d
INCcrtm=$(COREINC)/crtm

SIGIO_LIB=$(CORELIB)/v2.0.1/libsigio_v2.0.1_4.a

WRFPATH = /work/03337/tg826358/stampede2/WRFV3.8_GSD_hybridcoord
LIBwrfio_int    = $(WRFPATH)/external/io_int/libwrfio_int.a
LIBwrfio_netcdf = $(WRFPATH)/external/io_netcdf/libwrfio_nf.a
INCnetcdf       = ${NETCDF}/include
LIBnetcdf       = -L$(NETCDF)/lib -lnetcdf
OBJwrf_frame_pk = $(WRFPATH)/frame/pack_utils.o
OBJwrf_sizeof_int = $(WRFPATH)/frame/module_machine.o
WRFLIB = $(LIBwrfio_int) $(LIBwrfio_netcdf) $(OBJwrf_frame_pk) $(OBJwrf_sizeof_int)

NETCDF = /opt/apps/intel18/netcdf/4.3.3.1/x86_64
INCnetcdf       = ${NETCDF}/include
LIBnetcdf       = -L${NETCDF}/lib -lnetcdf -lnetcdff

# Empty out definition of libs use by GMAO GSI building structure
LIBtransf = #-L$(CORELIB) -ltransf
LIBhermes = #-L$(CORELIB) -lhermes
LIBgfio   = #-L$(CORELIB) -lgfio
INChdf    = #-I$(BASEDIR)/$(ARCH)/include/hdf
LIBhdf    = #-L$(BASEDIR)/$(ARCH)/lib  -lmfhdf -ldf -lhdfjpeg -lhdfz -lsz


# ---------------------------
# General targets/definitions
# ---------------------------

  AR     = ar -v

# ----------------------------
# Fortran compiler and options
# ----------------------------

  CF            = mpif90 -f90=ifort
  FC            = $(CF)

#--- Normal mode options
  PROF= #-pg
  OMP = #-qsmp=noauto

  FFLAGS_F90    =  -D_REAL8_ -DWRF

  FFLAGS_COM_N  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) -I $(INCnemsio) \
                -I $(INCnetcdf) -I $(INCw3) -O3 -traceback -assume byterecl \
                -g -fp-model source $(OMP) # -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512

  FFLAGS_COM_N_NOSWAP  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
                  -I $(INCnemsio) -I $(INCnetcdf) -I $(INCw3) -O3 -traceback -g \
                  -convert big_endian -fp-model source -assume byterecl $(OMP) #\
                  #-xCORE-AVX2 -axCORE-AVX512,MIC-AVX512

#  FFLAGS_COM_N  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) -I $(INCnemsio) \
#		-I $(INCnetcdf) -I $(INCw3) -O3 -xHOST -traceback -assume byterecl -convert big_endian $(OMP)

#  FFLAGS_COM_N_NOSWAP  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
#                  -I $(INCnemsio) -I $(INCnetcdf) -I $(INCw3) -O3 -xHOST -traceback $(OMP)

  FFLAGS_N  = $(FFLAGS_F90) $(FFLAGS_COM_N) $(PROF)
  FFLAGS_NOSWAP_N  = $(FFLAGS_F90) $(FFLAGS_COM_N_NOSWAP) $(PROF)
  FFLAGS_f  = $(FFLAGS_COM_N) $(PROF)
  FFLAGS    = $(FFLAGS_N) $(PROF)



#--- Debug mode options
  FFLAGS_COM_D  =  -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) -I $(INCnemsio) \
		-I $(INCnetcdf) -I $(INCw3) -O0 -xHOST -traceback -assume byterecl -convert big_endian
  FFLAGS_COM_NOSWAP_D  =  -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
		-I $(INCnemsio) -I $(INCnetcdf) -I $(INCw3) -O0 -xHOST -traceback
  
  FFLAGS_D  = $(FFLAGS_F90) $(FFLAGS_COM_D)
  FFLAGS_NOSWAP_D = $(FFLAGS_F90) $(FFLAGS_COM_NOSWAP_D)



# ----------------------
# C Compiler and options
# ----------------------

  CC            = gcc

#--- Normal mode options

  CFLAGS_N      = -DLINUX -Dfunder -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -O3 $(PROF)

#--- Debug mode options

  CFLAGS_D      = -DLINUX -Dfunder -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -g


# ------------------
# Linker and options
# ------------------

  LD            = $(CF) -mkl

#--- Normal mode options

  LIBS_N        = -L$(CORELIB) -lsp_d -lnemsio -lbacio_4 $(SIGIO_LIB) -lsigio_4 \
       -lsfcio_4 -lbufr_v10.2.3_d_64 -lw3nco_d -lw3emc_d -lcrtm $(WRFLIB) $(LIBnetcdf)

  LDFLAGS_N     = 

  LDFLAGS       = $(LDFLAGS_N)

#--- Debug mode options

  LIBS_D        = $(LIBS_N)

  LDFLAGS_D     =

#--- Empty out mpi library definition: embedded in compiler

  LIBmpi	= 
