# This config file contains the compile options for compilation
# of the GSI code on the NOAA HPCS.

# ----------------------------------
# Redefine variables for NOAA HPCS
# ----------------------------------

myhome=/work/03337/tg826358/stampede2/nmmb_lib
COREINC  = $(myhome)/incmod
CORELIB  =  -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/sfcio/1.4.1/lib \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/impi-2021.8.0/nemsio/2.5.4/lib64 \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/w3emc/2.9.2/lib64 \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/w3nco/2.4.1/lib \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/impi-2021.8.0/crtm/2.4.0/lib \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/sp/2.3.3/lib \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/bacio/2.4.1/lib \
            -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/bufr/11.7.0/lib64
INCsfcio = /scratch/ywang/tools/hpc-stack/intel-2021.8.0/sfcio/1.4.1/include
INCsigio = /scratch/ywang/tools/hpc-stack/intel-2021.8.0/sigio/2.3.2/include
INCnemsio= /scratch/ywang/tools/hpc-stack/intel-2021.8.0/impi-2021.8.0/nemsio/2.5.4/include
INCw3    = /scratch/ywang/tools/hpc-stack/intel-2021.8.0/w3emc/2.9.2/include_d
INCcrtm  = /scratch/ywang/tools/hpc-stack/intel-2021.8.0/impi-2021.8.0/crtm/2.4.0/include

SIGIO_LIB = -L/scratch/ywang/tools/hpc-stack/intel-2021.8.0/sigio/2.3.2/lib

WRFPATH   = /home/wofuser/WOFS/WRFV3.9_WOFS
LIBwrfio_int    = $(WRFPATH)/external/io_int/libwrfio_int.a
LIBwrfio_netcdf = $(WRFPATH)/external/io_netcdf/libwrfio_nf.a
INCnetcdf       = ${NETCDF}/include
LIBnetcdf       = -L$(NETCDF)/lib -lnetcdf
OBJwrf_frame_pk = $(WRFPATH)/frame/pack_utils.o
OBJwrf_sizeof_int = $(WRFPATH)/frame/module_machine.o
WRFLIB = $(LIBwrfio_int) $(LIBwrfio_netcdf) $(OBJwrf_frame_pk) $(OBJwrf_sizeof_int)

NETCDF          = /scratch/software/intel/netcdf
INCnetcdf       = ${NETCDF}/include
LIBnetcdf       = -L${NETCDF}/lib -lnetcdf -lnetcdff

# Empty out definition of libs use by GMAO GSI building structure
LIBtransf = #-L$(CORELIB) -ltransf
LIBhermes = #-L$(CORELIB) -lhermes
LIBgfio   = #-L$(CORELIB) -lgfio
INChdf    = #-I$(BASEDIR)/$(ARCH)/include/hdf
LIBhdf    = #-L$(BASEDIR)/$(ARCH)/lib  -lmfhdf -ldf -lhdfjpeg -lhdfz -lsz


# ---------------------------
# General targets/definitions
# ---------------------------

  AR     = ar -v

# ----------------------------
# Fortran compiler and options
# ----------------------------

  CF            = mpif90
  FC            = $(CF)

#--- Normal mode options
  PROF= #-pg
  OMP = #-qsmp=noauto

  FFLAGS_F90    =  -D_REAL8_ -DWRF

  FFLAGS_COM_N  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) -I $(INCnemsio) \
                -I $(INCnetcdf) -I $(INCw3) -O3 -traceback -assume byterecl \
                -g -fp-model source $(OMP) # -xCORE-AVX2 -axCORE-AVX512,MIC-AVX512

  FFLAGS_COM_N_NOSWAP  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
                  -I $(INCnemsio) -I $(INCnetcdf) -I $(INCw3) -O3 -traceback -g \
                  -convert big_endian -fp-model source -assume byterecl $(OMP) #\
                  #-xCORE-AVX2 -axCORE-AVX512,MIC-AVX512

#  FFLAGS_COM_N  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) -I $(INCnemsio) \
#		-I $(INCnetcdf) -I $(INCw3) -O3 -xHOST -traceback -assume byterecl -convert big_endian $(OMP)

#  FFLAGS_COM_N_NOSWAP  = -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
#                  -I $(INCnemsio) -I $(INCnetcdf) -I $(INCw3) -O3 -xHOST -traceback $(OMP)

  FFLAGS_N  = $(FFLAGS_F90) $(FFLAGS_COM_N) $(PROF)
  FFLAGS_NOSWAP_N  = $(FFLAGS_F90) $(FFLAGS_COM_N_NOSWAP) $(PROF)
  FFLAGS_f  = $(FFLAGS_COM_N) $(PROF)
  FFLAGS    = $(FFLAGS_N) $(PROF)



#--- Debug mode options
  FFLAGS_COM_D  =  -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) -I $(INCnemsio) \
		-I $(INCnetcdf) -I $(INCw3) -O0 -xHOST -traceback -assume byterecl -convert big_endian
  FFLAGS_COM_NOSWAP_D  =  -I ./ -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
		-I $(INCnemsio) -I $(INCnetcdf) -I $(INCw3) -O0 -xHOST -traceback

  FFLAGS_D  = $(FFLAGS_F90) $(FFLAGS_COM_D)
  FFLAGS_NOSWAP_D = $(FFLAGS_F90) $(FFLAGS_COM_NOSWAP_D)



# ----------------------
# C Compiler and options
# ----------------------

  CC            = gcc

#--- Normal mode options

  CFLAGS_N      = -DLINUX -Dfunder -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -O3 $(PROF)

#--- Debug mode options

  CFLAGS_D      = -DLINUX -Dfunder -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -g


# ------------------
# Linker and options
# ------------------

  LD            = $(CF) -qmkl

#--- Normal mode options

  LIBS_N        = $(CORELIB) -lsp_d -lnemsio -lbacio_4 $(SIGIO_LIB) -lsigio \
       -lsfcio -lbufr_d -lw3nco_d -lw3emc_d -lcrtm $(WRFLIB) $(LIBnetcdf)

  LDFLAGS_N     =

  LDFLAGS       = $(LDFLAGS_N)

#--- Debug mode options

  LIBS_D        = $(LIBS_N)

  LDFLAGS_D     =

#--- Empty out mpi library definition: embedded in compiler

  LIBmpi	=
